services:
  db:
    image: postgres:15
    container_name: guispin_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Guispin.Server/Dockerfile
    container_name: guispin_backend
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: "Host=${DB_HOST};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Guispin.Client/Dockerfile
    container_name: guispin_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data:
